# Generated by Django 5.1.6 on 2025-02-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0002_reservationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationitem',
            old_name='time',
            new_name='date',
        ),
    ]
